name: Test-Code
on: [push,workflow_dispatch]
jobs:
    test :
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v5
              #install NodeJS
            - name: Install Nodejs
              uses: actions/setup-node@v6
              with:
                  node-version: 24
            - name: version
              run: node -v
              #install dependencies
            - name: Dependencies
              run: npm ci
              #run test 
            - name: Run Test
              run: npm run test
    depoly:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v5

            - name: Install NodeJS
              uses: actions/setup-node@v6
              with:
                node-version: 20
            - name: Install Dependencies
              run: npm ci

            - name: Build Project
              run: npm run build

            - name: Deploy
              run: echo "Deply is Successful"