name: Test-Code
on: [push,workflow_dispatch]
jobs:
    test :
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              run: |
                echo "cloning the repo"
                git clone https://github.com/electra956/React_cicd_actions.git