name: Test-Code
on:
  push:
    branches:
      - main
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/*'
      - README.txt
jobs:
    test :
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v5
              #install NodeJS
            - name: Install Nodejs
              uses: actions/setup-node@v6
              with:
                  node-version: 24
            - name: version
              run: node -v
              #install dependencies
            - name: Dependencies
              run: npm ci
            - name: Cache Dependencies
              uses: actions/cache@v4
              with: 
                path: ~/.npm
                key: ${{runner.os}}-node-${{ hashFiles('**/package-lock.json') }}
              #run test 
            - name: Run Test
              run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v5

            - name: Install NodeJS
              uses: actions/setup-node@v6
              with:
                node-version: 20
            - name: Cache Dependencies
              uses: actions/cache@v4
              with: 
                path: ~/.npm
                key: ${{runner.os}}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
            - name: Upload Dist file
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: dist
    depoly:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Upload Dist file
              uses: actions/download-artifact@v4
              with:
                name: dist-files
                path: dist
            - name: Deploy
              run: echo "Deply is Successful"
