name: Test-Code
on: [push,workflow_dispatch]
jobs:
    test :
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              run: |
                echo "cloning the repo"
                echo "${{toJson(github)}}"
                git clone https://github.com/${{github.repository}}.git